"""高置信选股策略的配置常量与 rule_version 组合。

来源：app.py 顶部的 HC_* 常量块（约第 54-106 行）。运行时状态（缓存字典、
线程锁、进度表）不在这里，放 core.py。
"""
from __future__ import annotations

from trader.patterns.scanner import FOCUS_LONG_100YI_SIGNAL_COMBOS
from trader.strategies.high_confidence.focus_model import (
    DEFAULT_CALIBRATION_DATE as HC_FOCUS_MODEL_CALIBRATION_DATE,
    DEFAULT_THRESHOLD as HC_FOCUS_MODEL_THRESHOLD,
)

HC_DEFAULT_MAX_PER_DATE = 0
HC_DEFAULT_HISTORY_DAYS = 7
HC_FOCUS_SIGNAL_COMBOS = FOCUS_LONG_100YI_SIGNAL_COMBOS
HC_DEFAULT_PATTERNS = sorted({pattern for _fid, pattern, _family in HC_FOCUS_SIGNAL_COMBOS})
HC_DEFAULT_MIN_MARKET_CAP_YI = 100
HC_ENABLE_MARKET_CAP_FILTER = True
HC_KEEP_MISSING_MARKET_CAP = True
HC_ENABLE_REALTIME_MARKET_CAP = True
HC_ENABLE_QUALITY_CACHE = False
HC_ENABLE_QUALITY_CACHE_FALLBACK = False
HC_QUALITY_LOOKBACK_DAYS = 4200
HC_QUALITY_FORWARD_DAYS = 5
HC_QUALITY_OUTCOME = "max_high"
HC_QUALITY_WIN_RETURN_THRESHOLD = 0.02
HC_QUALITY_MIN_SAMPLES = 31
HC_QUALITY_MIN_WIN_RATE = 0.70
HC_ENABLE_FOCUS_MODEL = False
HC_ENABLE_PRECISION_FILTER = True
HC_PRECISION_RULE_VERSION = "precision_top5_p75"
HC_SCAN_LOOKBACK_DAYS = 400
HC_SCAN_MIN_HISTORY = 120
HC_SCAN_MODE = "loose"
HC_SCAN_PATTERN_ENGINE = "lizi_relaxed"
HC_SCAN_COUPLING_MATCH_MODE = "rule"
HC_QUALITY_COUPLING_MATCH_MODE = "rule"
HC_SHAPE_RULE_VERSION = "shape_lizi_relaxed6_fid18_fid47_fid26_fid19_fid23"
HC_MIN_FULL_MARKET_ROWS = 4500
HC_FOCUS_RULE_PART = (
    f"_focuson_noleak_ft{int(HC_FOCUS_MODEL_THRESHOLD * 1000)}"
    if HC_ENABLE_FOCUS_MODEL
    else "_focusoff"
)
HC_PRECISION_RULE_PART = (
    f"_{HC_PRECISION_RULE_VERSION}"
    if HC_ENABLE_PRECISION_FILTER
    else "_precisionoff"
)
HC_RULE_VERSION = (
    f"hc_{HC_SCAN_MODE}_{HC_SCAN_PATTERN_ENGINE}"
    f"_{HC_SHAPE_RULE_VERSION}"
    f"_scan{HC_SCAN_COUPLING_MATCH_MODE}"
    f"_qual{HC_QUALITY_COUPLING_MATCH_MODE}"
    f"_q{int(HC_QUALITY_MIN_WIN_RATE * 100)}"
    f"_s{HC_QUALITY_MIN_SAMPLES}"
    f"_fwd{HC_QUALITY_FORWARD_DAYS}_{HC_QUALITY_OUTCOME}"
    f"_wr{int(HC_QUALITY_WIN_RETURN_THRESHOLD * 100)}"
    f"{HC_FOCUS_RULE_PART}"
    f"{HC_PRECISION_RULE_PART}"
    f"_max{HC_DEFAULT_MAX_PER_DATE}"
    f"_cap{'on' if HC_ENABLE_MARKET_CAP_FILTER else 'off'}"
    f"_capmiss{'keep' if HC_KEEP_MISSING_MARKET_CAP else 'drop'}"
)
HC_FOCUS_MODEL_TRAIN_RULE_VERSION = HC_RULE_VERSION.replace(HC_FOCUS_RULE_PART, "").replace(HC_PRECISION_RULE_PART, "")
