"""形态策略：四针/底部反转扫描、历史回填、结果查询。"""
from trader.strategies.pattern.params import (
    build_pattern_params,
    build_cli_pattern_params,
    public_pattern_params,
    saved_pattern_filters_enabled,
    build_empty_pattern_meta,
    default_pattern_backfill_days,
    normalize_pattern_backfill_params,
    pattern_history_load_days,
    pattern_type_from_params_json,
)
from trader.strategies.pattern.candle import (
    candle_metrics,
    is_small_body_candle,
    is_doji_candle,
    has_balanced_shadows,
    candle_body_mid,
    pct_distance,
    four_pin_levels,
    build_candlestick_chart,
    candle_shape as candle_shape_simple,
    is_long_body as is_long_body_simple,
    load_daily_histories_for_pattern,
    load_daily_histories_for_pattern_range,
)
from trader.strategies.pattern.detection import (
    candle_shape,
    is_long_body,
    BOTTOM_PATTERN_GROUP_NAMES,
    BOTTOM_STRONG_PATTERNS,
    BOTTOM_SINGLE_PIN_PATTERNS,
    bottom_pattern_group,
    bottom_pattern_allowed_names,
    bottom_reversal_context,
    detect_bottom_reversal,
    bottom_reversal_confirmation,
    bottom_reversal_weak_filter,
    bottom_reversal_signal_at,
    bottom_pattern_history_stats,
    bottom_pattern_history_bonus,
    evaluate_four_pin_candidate,
    evaluate_bottom_reversal_candidate,
    evaluate_pattern_candidate,
)
from trader.strategies.pattern.storage import (
    ensure_pattern_tables,
    save_pattern_progress,
    load_pattern_progress,
    pattern_run_params,
    pattern_run_matches_type,
    delete_existing_pattern_scope,
    delete_pattern_history,
    save_pattern_scan_result,
    saved_pattern_row_passes_filters,
    load_pattern_rows_for_run,
    load_latest_pattern_result,
    load_pattern_history,
)
from trader.strategies.pattern.scan import (
    fetch_eastmoney_market_caps,
    apply_market_cap_filter,
    perform_pattern_scan,
    perform_pattern_scan_with_histories,
    get_pattern_backfill_trade_dates,
    run_pattern_backfill,
    run_pattern_backfill_job,
)
